site_name: MkDocs
site_url: https://docs.composable.ai
site_description: Composable DataOps Platform technical documentation for big data orchestration, automation and analytics
site_author: Composable Analytics, Inc.

repo_url: https://github.com/ComposableAnalytics/Docs

theme:
    name: mkdocs
    highlightjs: true

pages:
- Home: 'index.md'
- About: 'about/about.md'
- Documentation:
    - 1. Getting Started:
        - '1.1 Overview': '01.Getting-Started/01.Overview.md'
        - '1.2 System requirements': '01.Getting-Started/02.System-Requirements.md'
        - '1.3 Installation and Deployment': '01.Getting-Started/03.Installation-and-Deployment.md'
    - 2. Composable Platform:
        - '2.1 Overview': '02.Composable-Platform/01.Overview.md'    
    - 3. DataFlows:
        - '3.1 Overview': '03.DataFlows/01.Overview.md'
        - '3.2 Composable Designer': '03.DataFlows/02.Composable-Designer.md'
        - '3.3 KeyBoard Shortcuts': '03.DataFlows/03.KeyBoard-Shortcuts.md'
        - '3.4 Modules': '03.DataFlows/04.Modules.md'
        - '3.5 DataFlows': '03.DataFlows/05.DataFlows.md'
        - '3.6 DataFlow Reuse': '03.DataFlows/06.DataFlow-Reuse.md'
        - '3.7 Alerts': '03.DataFlows/07.Alerts.md'
        - 3.8 Data Sources:
            - '3.8 Data Sources': '03.DataFlows/08.Data-Sources/01.Overview.md'
        - 3.9 Analytics:
            - '3.9 Analytics': '03.DataFlows/09.Analytics/01.Overview.md'
        - 3.10 DataFlow Patterns:
            - '3.10 DataFlow Patterns': '03.DataFlows/10.DataFlow-Patterns/01.Overview.md'
    - 4. QueryViews:
        - '4.1 Overview': '04.Dataflows/01.Overview.md'
    - 5. DataPortals:
        - '5.1 Overview': '05.DataPortals/01.Overview.md'
    - 6. DataExplorer:
        - '6.1 Overview': '06.DataExplorer/01.Overview.md'
    - 7. DashBoards:
        - '7.1 Overview': '07.DashBoards/01.Overview.md'
    - 8. WebApps:
        - '8.1 Overview': '08.WebApps/01.Overview.md'
    - 9. Keys:
        - '9.1 Overview': '09.Keys/01.Overview.md'
    - 10. Users and Groups:
        - '10.1 Overview': '10.Users-and-Groups/01.Overview.md'
    - 11. FluentAPI:
        - '11.1 FluentAPI User Guide': '11.FluentAPI/01.FluentAPI-User-Guide.md'
        - '11.2 FluentAPI Reference': '11.FluentAPI/02.FluentAPI-Reference.md'
    - 12. How to Articles:
        - '12.1 Overview': '12.How-To-Articles/10.1-Overview.md'
    - 13. Quick Reference Guides:
        - '13.1 Overview': '13.Quick-Reference-Guides/01.Overview.md'

markdown_extensions:
  - admonition
  
html_logo = 'img/composable.png'