site_name: Composable DataOps Platform
site_url: https://docs.composable.ai
site_description: Composable DataOps Platform technical documentation for big data orchestration, automation and analytics
site_author: Composable Analytics, Inc.

repo_url: https://github.com/ComposableAnalytics/Docs

theme:
    name: readthedocs
    highlightjs: true

pages:
- Home: 'index.md'
- About: 'about/about.md'
- Documentation:
    - 1. Getting Started:
        - '1.1 Overview': '01.Getting-Started/01.Overview.md'
        - '1.2 System requirements': '01.Getting-Started/02.System-Requirements.md'
        - '1.3 Installation and Deployment': '01.Getting-Started/03.Installation-and-Deployment.md'
        - '1.4 Public Cloud Deployment': '01.Getting-Started/04.Public-Cloud-Deployment.md'
    - 2. Composable Platform:
        - '2.1 Overview': '02.Composable-Platform/01.Overview.md'
        - '2.2 Navigation': '02.Composable-Platform/02.Navigation.md'
        - '2.3 Search': '02.Composable-Platform/03.Search.md'
        - '2.4 Product Areas': '02.Composable-Platform/04.Product-Areas.md'
        - '2.5 System Administration': '02.Composable-Platform/05.System-Administration.md'
    - 3. DataFlows:
        - '3.1 Overview': '03.DataFlows/01.Overview.md'
        - '3.2 Composable Designer': '03.DataFlows/02.Composable-Designer.md'
        - '3.3 KeyBoard Shortcuts': '03.DataFlows/03.KeyBoard-Shortcuts.md'
        - '3.4 Modules': '03.DataFlows/04.Modules.md'
        - '3.5 DataFlows': '03.DataFlows/05.DataFlows.md'
        - '3.6 DataFlow Reuse': '03.DataFlows/06.DataFlow-Reuse.md'
        - '3.7 Custom Module Extensions': '03.DataFlows/07.Custom-Modules.md'
        - '3.8 Example DataFlows': '03.DataFlows/08.Example-DataFlows.md'
        - 3.9 Module Details:
            - 'DataPortal Delete': '03.DataFlows/09.Module-Details/DataPortalDelete.md'
            - 'DataPortal Sync': '03.DataFlows/09.Module-Details/DataPortalSync.md'
    - 4. QueryViews:
        - '4.1 Overview': '04.QueryViews/01.Overview.md'
        - '4.2 QueryView Creation': '04.QueryViews/02.Create-QueryView.md'
    - 5. DataPortals:
        - '5.1 Overview': '05.DataPortals/01.Overview.md'
        - '5.2 DataPortal Creation': '05.DataPortals/02.Create-DataPortals.md'
        - '5.3 Search': '05.DataPortals/03.Search-Features.md'
        - '5.4 Categories': '05.DataPortals/04.Categories.md'
        - 5.5 Control Type Details:
            - 'AppRun': '05.DataPortals/05.Control-Details/AppRun.md'
            - 'Category': '05.DataPortals/05.Control-Details/Category.md'
            - 'ClearButton': '05.DataPortals/05.Control-Details/ClearButton.md'
            - 'CheckBox': '05.DataPortals/05.Control-Details/CheckBox.md'
            - 'Computed': '05.DataPortals/05.Control-Details/Computed.md'
            - 'Date': '05.DataPortals/05.Control-Details/Date.md'
            - 'DateTime': '05.DataPortals/05.Control-Details/DateTime.md'
            - 'HyperLink': '05.DataPortals/05.Control-Details/HyperLink.md'
            - 'Label': '05.DataPortals/05.Control-Details/Label.md'
            - 'Link': '05.DataPortals/05.Control-Details/Link.md'
            - 'NumberFormatting': '05.DataPortals/05.Control-Details/NumberFormatting.md'
            - 'Page': '05.DataPortals/05.Control-Details/Page.md'
            - 'Phone': '05.DataPortals/05.Control-Details/Phone.md'
            - 'QueryView': '05.DataPortals/05.Control-Details/QueryView.md'
            - 'QueryViewChooser': '05.DataPortals/05.Control-Details/QueryViewChooser.md'
            - 'Radio': '05.DataPortals/05.Control-Details/Radio.md'
            - 'Rating': '05.DataPortals/05.Control-Details/Rating.md'
            - 'Reference': '05.DataPortals/05.Control-Details/Reference.md'
            - 'SaveButton': '05.DataPortals/05.Control-Details/SaveButton.md'
            - 'Spin': '05.DataPortals/05.Control-Details/Spin.md'
            - 'SSN': '05.DataPortals/05.Control-Details/SSN.md'
            - 'Tab': '05.DataPortals/05.Control-Details/Tab.md'
            - 'Table': '05.DataPortals/05.Control-Details/Table.md'
            - 'Text': '05.DataPortals/05.Control-Details/Text.md'
            - 'Textarea': '05.DataPortals/05.Control-Details/Textarea.md'
            - 'Voice': '05.DataPortals/05.Control-Details/Voice.md'
            - 'YesNo': '05.DataPortals/05.Control-Details/YesNo.md'
            - 'ZIP': '05.DataPortals/05.Control-Details/ZIP.md'
        - 5.6 Setting Details:
            - 'AfterSaveUri': '05.DataPortals/06.Setting-Details/AfterSaveUri.md'
            - 'ClearWhenHidden': '05.DataPortals/06.Setting-Details/ClearWhenHidden.md'
            - 'Columns': '05.DataPortals/06.Setting-Details/Columns.md'
            - 'ComputedCondition': '05.DataPortals/06.Setting-Details/ComputedCondition.md'
            - 'ControlGroup': '05.DataPortals/06.Setting-Details/ControlGroup.md'
            - 'ControlType': '05.DataPortals/06.Setting-Details/ControlType.md'
            - 'CustomIndex': '05.DataPortals/06.Setting-Details/CustomIndex.md'
            - 'DefaultSearchFilter': '05.DataPortals/06.Setting-Details/DefaultSearchFilter.md'
            - 'DefaultValue': '05.DataPortals/06.Setting-Details/DefaultValue.md'
            - 'DeleteType': '05.DataPortals/06.Setting-Details/DeleteType.md'
            - 'Description': '05.DataPortals/06.Setting-Details/Description.md'
            - 'DisplayName': '05.DataPortals/06.Setting-Details/DisplayName.md'
            - 'EndLabel': '05.DataPortals/06.Setting-Details/EndLabel.md'
            - 'FormattingLocale': '05.DataPortals/06.Setting-Details/FormattingLocale.md'
            - 'FormattingOptions': '05.DataPortals/06.Setting-Details/FormattingOptions.md'
            - 'Group': '05.DataPortals/06.Setting-Details/Group.md'
            - 'Href': '05.DataPortals/06.Setting-Details/Href.md'
            - 'InvalidMessage': '05.DataPortals/06.Setting-Details/InvalidMessage.md'
            - 'MaskedCondition': '05.DataPortals/06.Setting-Details/MaskedCondition.md'
            - 'Max': '05.DataPortals/06.Setting-Details/Max.md'
            - 'Min': '05.DataPortals/06.Setting-Details/Min.md'
            - 'Name': '05.DataPortals/06.Setting-Details/Name.md'
            - 'OptionController': '05.DataPortals/06.Setting-Details/OptionController.md'
            - 'Pattern': '05.DataPortals/06.Setting-Details/Pattern.md'
            - 'PatternFlags': '05.DataPortals/06.Setting-Details/PatternFlags.md'
            - 'ReadOnlyCondition': '05.DataPortals/06.Setting-Details/ReadOnlyCondition.md'
            - 'RefreshComponents': '05.DataPortals/06.Setting-Details/RefreshComponents.md'
            - 'Required': '05.DataPortals/06.Setting-Details/Required.md'
            - 'SaveBeforeRun': '05.DataPortals/06.Setting-Details/SaveBeforeRun.md'
            - 'SearchBoxes': '05.DataPortals/06.Setting-Details/SearchBoxes.md'
            - 'Separator': '05.DataPortals/06.Setting-Details/Separator.md'
            - 'StartLabel': '05.DataPortals/06.Setting-Details/StartLabel.md'
            - 'StrMax': '05.DataPortals/06.Setting-Details/StrMax.md'
            - 'StrMin': '05.DataPortals/06.Setting-Details/StrMin.md'
            - 'Style': '05.DataPortals/06.Setting-Details/Style.md'
            - 'TabIndex': '05.DataPortals/06.Setting-Details/TabIndex.md'
            - 'Target': '05.DataPortals/06.Setting-Details/Target.md'
            - 'Type': '05.DataPortals/06.Setting-Details/Type.md'
            - 'UniqueConstraint': '05.DataPortals/06.Setting-Details/UniqueConstraint.md'
            - 'UniqueConstraintScopeToParent': '05.DataPortals/06.Setting-Details/UniqueConstraintScopeToParent.md'
            - 'ValidationCondition': '05.DataPortals/06.Setting-Details/ValidationCondition.md'
            - 'VisibilityCondition': '05.DataPortals/06.Setting-Details/VisibilityCondition.md'
    - 6. DataExplorer:
        - '6.1 Overview': '06.DataExplorer/01.Overview.md'
    - 7. DashBoards:
        - '7.1 Overview': '07.DashBoards/01.Overview.md'
    - 8. WebApps:
        - '8.1 Overview': '08.WebApps/01.Overview.md'
    - 9. Keys:
        - '9.1 Overview': '09.Keys/01.Overview.md'
        - '9.2 Using Keys': '09.Keys/02.Using-Keys.md'
    - 10. Users and Groups:
        - '10.1 Overview': '10.Users-and-Groups/01.Overview.md'
    - 11. FluentAPI:
        - '11.1 FluentAPI User Guide': '11.FluentAPI/01.FluentAPI-User-Guide.md'
        - '11.2 FluentAPI Reference': '11.FluentAPI/02.FluentAPI-Reference.md'
    - 12. Code Promotion:
        - '12.1 Overview': '12.Code-Promotion/01.Overview.md'
        - '12.2 Setup': '12.Code-Promotion/02.Setup.md'
        - '12.3 Optional Settings': '12.Code-Promotion/03.Optional-Settings.md'
        - '12.4 Possible-Issues': '12.Code-Promotion/04.Possible-Issues.md'
    
markdown_extensions:
  - admonition
