site_name: Composable DataOps Platform Knowledge Base
pages:
- Home: 'index.md'
- About: 'about/about.md'
- Documentation:
    - 1. Getting Started:
        - '1.1 Overview': '01.Getting-Started/01.Overview.md'
        - '1.2 System requirements': '01.Getting-Started/02.System-Requirements.md'
        - '1.3 Installation and Deployment': '01.Getting-Started/03.Installation-and-Deployment.md'
    - 2. DataFlows:
        - '3.1 Overview': '3.-Dataflows/3.1-Overview.md'
    - 3. QueryViews:
        - '3.1 Overview': '3.-Dataflows/3.1-Overview.md'
    - 4. Boards:
        - '4.1 Overview': '4.-Boards/4.1-Overview.md'
    - 5. Dynamic Forms:
        - '5.1 Overview': '5.-Dynamic-Forms/5.1-Overview.md'
    - 6. Data Sources:
        - '6.1 Overview': '6.-Data-Sources/6.1-Overview.md'
    - 7. Analytics:
        - '7.1 Overview': '7.-Analytics/7.1-Overview.md'
    - 8. Properties:
        - '8.1 Overview': '8.-Properties/8.1-Overview.md'
    - 9. Groups:
        - '9.1 Overview': '9.-Groups/9.1-Overview.md'
    - 10. FluentAPI:
        - '10.1 FluentAPI User Guide': '10.-FluentAPI/10.1-FluentAPI-User-Guide.md'
        - '10.2 FluentAPI Reference': '10.-FluentAPI/10.2-FluentAPI-Reference.md'
    - 10. How to Articles:
        - '10.1 Overview': '10.-How-To-Articles/10.1-Overview.md'
    - 11. How to Articles:
        - '11.1 Overview': '11.-How-To-Articles/11.1-Overview.md'
    - 11. Quick Reference Guides:
        - '11.1 Overview': '11.-Quick-Reference-Guides/11.1-Overview.md'
        - '11.2 KeyBoard Shortcuts': '11.-Quick-Reference-Guides/11.2-KeyBoard-Shortcuts.md'
    - 12. Quick Reference Guides:
        - '12.1 Overview': '12.-Quick-Reference-Guides/12.1-Overview.md'
        - '12.2 KeyBoard Shortcuts': '12.-Quick-Reference-Guides/12.2-KeyBoard-Shortcuts.md'
theme: readthedocs
